import { useEffect, useState } from "react";
import type { DesktopApi, ExportPrepareResult, SetDraftSnapshot } from "../../../../shared/contracts";

export function ExportPanel({ api, snapshot, disabled = false }: { api: DesktopApi | null; snapshot: SetDraftSnapshot; disabled?: boolean }) {
  const [prepared, setPrepared] = useState<ExportPrepareResult | null>(null); const [message, setMessage] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  useEffect(() => { setPrepared(null); }, [disabled, snapshot.contentRevision, snapshot.currentRevision, snapshot.draftId]);
  async function prepare() { if (disabled) return; if (!api) { setMessage("Export is unavailable."); return; } setBusy(true); setMessage(null); try { const result = await api.exports.prepare({ draftId: snapshot.draftId, expectedRevision: snapshot.currentRevision }); setPrepared(result); if (result.status === "cancelled") setMessage("Export cancelled."); } catch { setMessage("Export preparation failed. Your draft is unchanged."); } finally { setBusy(false); } }
  async function confirm() { if (disabled || !api || !prepared || prepared.status !== "ready") return; setBusy(true); try { const result = await api.exports.confirm({ confirmationId: prepared.confirmationId }); setMessage(result.status === "exported" ? `Exported ${result.playlistName}` : "Export was blocked at the selected destination."); } catch { setMessage("Export confirmation failed."); } finally { setBusy(false); } }
  return <section aria-labelledby="export-title"><h2 id="export-title">Export</h2><p>Choose the destination only in the native confirmation step.</p>{disabled && <p>Return to the current draft or restore this version before exporting.</p>}<button type="button" disabled={busy || disabled} onClick={() => void prepare()}>Prepare Rekordbox XML export</button>{prepared?.status === "blocked" && <div role="alert"><p>Export is blocked.</p><ul>{prepared.reasons.map((reason) => <li key={reason.code}>{reason.message}</li>)}</ul></div>}{prepared?.status === "ready" && <div><p>Ready: {prepared.destinationDisplay}</p><p>{prepared.willReplaceExisting ? "This will replace the existing file." : "This creates a new file."}</p>{prepared.warnings.map((warning) => <p key={warning}>{warning}</p>)}<button type="button" disabled={busy || disabled} onClick={() => void confirm()}>Confirm export</button></div>}{message && <p role="status">{message}</p>}</section>;
}
