import { useState } from "react";
import type { DesktopApi, ExportPrepareResult, SetDraftSnapshot } from "../../../../shared/contracts";

export function ExportPanel({ api, snapshot }: { api: DesktopApi | null; snapshot: SetDraftSnapshot }) {
  const [prepared, setPrepared] = useState<ExportPrepareResult | null>(null); const [message, setMessage] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  async function prepare() { if (!api) { setMessage("Export is unavailable."); return; } setBusy(true); setMessage(null); try { const result = await api.exports.prepare({ draftId: snapshot.draftId, expectedRevision: snapshot.currentRevision }); setPrepared(result); if (result.status === "cancelled") setMessage("Export cancelled."); } catch { setMessage("Export preparation failed. Your draft is unchanged."); } finally { setBusy(false); } }
  async function confirm() { if (!api || !prepared || prepared.status !== "ready") return; setBusy(true); try { const result = await api.exports.confirm({ confirmationId: prepared.confirmationId }); setMessage(result.status === "exported" ? `Exported ${result.playlistName}` : "Export was blocked at the selected destination."); } catch { setMessage("Export confirmation failed."); } finally { setBusy(false); } }
  return <section aria-labelledby="export-title"><h2 id="export-title">Export</h2><p>Choose the destination only in the native confirmation step.</p><button type="button" disabled={busy} onClick={() => void prepare()}>Prepare Rekordbox XML export</button>{prepared?.status === "blocked" && <div role="alert"><p>Export is blocked.</p><ul>{prepared.reasons.map((reason) => <li key={reason.code}>{reason.message}</li>)}</ul></div>}{prepared?.status === "ready" && <div><p>Ready: {prepared.destinationDisplay}</p>{prepared.warnings.map((warning) => <p key={warning}>{warning}</p>)}<button type="button" disabled={busy} onClick={() => void confirm()}>Confirm export</button></div>}{message && <p role="status">{message}</p>}</section>;
}
