import { useCallback, useEffect, useRef, useState } from "react";
import type { DesktopApi, DiscoveryTrack, SetDraftMutationRequest, SetDraftReplacementResult, SetDraftSnapshot } from "../../../../shared/contracts";
import { DraftTrackList } from "./DraftTrackList";
import { ExportPanel } from "./ExportPanel";
import { SetInspectionPanel } from "./SetInspectionPanel";

export function SetWorkspace({ api, snapshot, availableTracks, onSnapshot, onClose }: { api: DesktopApi | null; snapshot: SetDraftSnapshot; availableTracks: DiscoveryTrack[]; onSnapshot(snapshot: SetDraftSnapshot): void; onClose(): void }) {
  const [current, setCurrent] = useState(snapshot); const [message, setMessage] = useState<string | null>(null); const [version, setVersion] = useState(""); const requestId = useRef(0);
  useEffect(() => setCurrent(snapshot), [snapshot]);
  const mutate = useCallback(async (mutation: SetDraftMutationRequest["mutation"]) => { if (!api) { setMessage("Set editing is unavailable."); return; } const id = ++requestId.current; try { const response = await api.sets.mutate({ draftId: current.draftId, expectedRevision: current.currentRevision, mutation }); if (id !== requestId.current) return; if (response.status === "updated") { setCurrent(response.snapshot); onSnapshot(response.snapshot); setMessage("Draft updated."); } else { const refreshed = await api.sets.get({ draftId: current.draftId }); if (id === requestId.current) { setCurrent(refreshed); onSnapshot(refreshed); setMessage("Set changed elsewhere. Reloaded current draft."); } } } catch { if (id === requestId.current) setMessage("The draft could not be updated. It remains unchanged."); } }, [api, current, onSnapshot]);
  const findReplacements = useCallback(async (entryId: string): Promise<SetDraftReplacementResult | null> => { if (!api) return null; try { return await api.sets.findReplacements({ draftId: current.draftId, entryId, ...(current.contentRevision === current.currentRevision ? {} : { revision: current.contentRevision }) }); } catch { setMessage("Replacement suggestions could not be loaded."); return null; } }, [api, current]);
  const viewVersion = useCallback(async (revision?: number) => { if (!api) return; const id = ++requestId.current; try { const response = await api.sets.get({ draftId: current.draftId, ...(revision === undefined ? {} : { revision }) }); if (id === requestId.current) { setCurrent(response); setMessage(revision === undefined ? "Viewing current draft." : "Viewing saved version."); } } catch { if (id === requestId.current) setMessage("The requested draft version could not be loaded."); } }, [api, current.draftId]);
  useEffect(() => { const handler = (event: KeyboardEvent) => { if (!event.metaKey || event.key.toLowerCase() !== "z") return; event.preventDefault(); void mutate({ type: event.shiftKey ? "redo" : "undo" }); }; window.addEventListener("keydown", handler); return () => window.removeEventListener("keydown", handler); }, [mutate]);
  const readOnly = current.viewingVersion !== null || current.contentRevision !== current.currentRevision;
  return <section className="set-workspace" aria-labelledby="set-workspace-title"><div className="set-workspace-heading"><h2 id="set-workspace-title">{current.title}</h2><button type="button" onClick={onClose}>Back to library</button></div><p aria-live="polite">{message}</p>{readOnly && <p role="status">Viewing a saved version. Restore it to edit the current draft.</p>}
    <label>Set title <input aria-label="Set title" disabled={readOnly} value={current.title} onChange={(event) => setCurrent({ ...current, title: event.target.value })} onBlur={(event) => event.target.value.trim() && void mutate({ type: "rename", title: event.target.value.trim() })} /></label>
    <label>Set intent <select aria-label="Set intent" disabled={readOnly} value={current.plan.intent} onChange={(event) => void mutate({ type: "set_plan", plan: { ...current.plan, intent: event.target.value as typeof current.plan.intent } })}><option value="smooth">Smooth</option><option value="build">Build</option><option value="peak">Peak</option><option value="reset">Reset</option><option value="genre_shift">Genre shift</option><option value="adventurous">Adventurous</option><option value="singalong_continuation">Singalong continuation</option><option value="closer">Closer</option></select></label>
    <label>Target duration (minutes)<input aria-label="Target duration (minutes)" type="number" min="15" max="480" disabled={readOnly} defaultValue={current.plan.targetDurationMs === null ? "" : current.plan.targetDurationMs / 60_000} onBlur={(event) => { const minutes = event.target.value === "" ? null : Number(event.target.value); if (minutes === null || (Number.isFinite(minutes) && minutes >= 15 && minutes <= 480)) void mutate({ type: "set_plan", plan: { ...current.plan, targetDurationMs: minutes === null ? null : Math.round(minutes * 60_000) } }); }} /></label>
    <label>Maximum artist repeats<input aria-label="Maximum artist repeats" type="number" min="1" max="20" disabled={readOnly} defaultValue={current.plan.maxArtistRepeats ?? ""} onBlur={(event) => { const repeats = event.target.value === "" ? null : Number(event.target.value); if (repeats === null || (Number.isInteger(repeats) && repeats >= 1 && repeats <= 20)) void mutate({ type: "set_plan", plan: { ...current.plan, maxArtistRepeats: repeats } }); }} /></label>
    <div className="set-actions"><button type="button" disabled={readOnly} onClick={() => void mutate({ type: "optimize" })}>Optimize order</button><button type="button" disabled={readOnly || !current.canUndo} onClick={() => void mutate({ type: "undo" })}>Undo</button><button type="button" disabled={readOnly || !current.canRedo} onClick={() => void mutate({ type: "redo" })}>Redo</button><button type="button" disabled={readOnly} onClick={() => void mutate({ type: "save_version", label: `Version ${current.currentRevision}` })}>Save version</button></div>
    <label>Saved versions <select aria-label="Saved versions" value={version} onChange={(event) => setVersion(event.target.value)}><option value="">Select a version</option>{current.versions.map((item) => <option key={item.version} value={item.version}>{item.label}</option>)}</select></label><button type="button" disabled={!version} onClick={() => { const selected = current.versions.find((item) => item.version === Number(version)); if (selected) void viewVersion(selected.revision); }}>View selected version</button><button type="button" disabled={!version} onClick={() => void mutate({ type: "restore_version", version: Number(version) })}>Restore version</button>{readOnly && <button type="button" onClick={() => void viewVersion()}>View current draft</button>}
    <DraftTrackList snapshot={current} availableTracks={availableTracks} readOnly={readOnly} onMutate={mutate} onFindReplacements={findReplacements} />
    <SetInspectionPanel api={api} request={{ kind: "draft", draftId: current.draftId, ...(current.contentRevision === current.currentRevision ? {} : { revision: current.contentRevision }) }} /><ExportPanel api={api} snapshot={current} />
  </section>;
}
