#!/bin/sh

set -eu

if [ "$#" -lt 1 ] || [ "$#" -gt 2 ]; then
  printf '%s\n' "usage: collect-phase0-environment.sh OUTPUT_PATH [REKORDBOX_APP_PATH]" >&2
  exit 2
fi

output_path=$1
requested_rekordbox_application=${2:-}
output_directory=${output_path%/*}
if [ "$output_directory" = "$output_path" ]; then
  output_directory=.
fi
/bin/mkdir -p "$output_directory"
temporary_path=$(/usr/bin/mktemp "${output_path}.tmp.XXXXXX")
trap '/bin/rm -f "$temporary_path"' EXIT HUP INT TERM

first_meaningful_line() {
  "$@" 2>&1 | /usr/bin/sed -n '/^WARNING:/d; /^[[:space:]]*$/d; p; q'
}

tool_version() {
  label=$1
  command_name=$2
  shift 2
  if command -v "$command_name" >/dev/null 2>&1; then
    version=$(first_meaningful_line "$command_name" "$@" || true)
    if [ -z "$version" ]; then
      version="installed; version command returned no text"
    fi
  else
    version="not installed on PATH"
  fi
  printf -- '- %s: %s\n' "$label" "$version" >>"$temporary_path"
}

{
  printf '%s\n' "# Phase 0 Local Environment"
  printf '\n'
  printf '%s\n' "Generated by the read-only environment collector. Optional tools may be absent."
  printf '\n'
  printf '%s\n' "## Host"
  printf '\n'
  printf -- '- Collected at (UTC): %s\n' "$(/bin/date -u '+%Y-%m-%dT%H:%M:%SZ')"
  printf -- '- macOS: %s\n' "$(/usr/bin/sw_vers -productVersion 2>/dev/null || printf unknown)"
  printf -- '- Architecture: %s\n' "$(/usr/bin/uname -m)"
  printf -- '- Kernel: %s\n' "$(/usr/bin/uname -r)"
  printf '\n'
  printf '%s\n' "## Toolchain"
  printf '\n'
} >"$temporary_path"

tool_version "Git" git --version
tool_version "Node.js" node --version
tool_version "npm" npm --version
tool_version "pnpm" pnpm --version
tool_version "Python" python3 --version
tool_version "uv" uv --version
tool_version "ffmpeg" ffmpeg -version
tool_version "ffprobe" ffprobe -version
tool_version "Codex CLI" codex --version

{
  printf '\n'
  printf '%s\n' "## Local applications"
  printf '\n'
} >>"$temporary_path"

if command -v codex >/dev/null 2>&1; then
  if codex login status >/dev/null 2>&1; then
    printf '%s\n' '- Codex authentication: existing login status is available (no credential material inspected)' >>"$temporary_path"
  else
    printf '%s\n' '- Codex authentication: CLI is installed but existing login status is unavailable' >>"$temporary_path"
  fi
else
  printf '%s\n' '- Codex authentication: Codex CLI is not installed on PATH' >>"$temporary_path"
fi

rekordbox_application=$requested_rekordbox_application
if [ -n "$rekordbox_application" ]; then
  :
elif [ -d "/Applications/rekordbox.app" ]; then
  rekordbox_application="/Applications/rekordbox.app"
elif [ -d "/Applications/rekordbox 7/rekordbox.app" ]; then
  rekordbox_application="/Applications/rekordbox 7/rekordbox.app"
elif command -v mdfind >/dev/null 2>&1; then
  rekordbox_application=$(mdfind 'kMDItemFSName == "rekordbox.app"cd' 2>/dev/null | /usr/bin/sed -n '1p')
fi

if [ -n "$rekordbox_application" ] && [ -f "$rekordbox_application/Contents/Info.plist" ]; then
  rekordbox_version=$(
    /usr/libexec/PlistBuddy -c 'Print :CFBundleShortVersionString' \
      "$rekordbox_application/Contents/Info.plist" 2>/dev/null || true
  )
  if [ -z "$rekordbox_version" ]; then
    rekordbox_version="installed; version unavailable"
  fi
  printf -- '- Rekordbox: %s\n' "$rekordbox_version" >>"$temporary_path"
else
  printf '%s\n' '- Rekordbox: not found in standard application locations or Spotlight index' >>"$temporary_path"
fi

/bin/mv "$temporary_path" "$output_path"
trap - EXIT HUP INT TERM
